### PR TITLE
265 blocked hello message

### LINKED ISSUE #265: Hello message
To test the request/reply functionality, let's implement the Hello request and reply.  These are specified in [§ 6.3.4](https://docs.google.com/document/d/1W0NDiHSKVvnVx5QytaxD00uUaoA6t9YU/edit#heading=h.42ddq1a).  Notably, the `Hello` message is empty (so we don't need to define a struct for it).  Define a struct for the response, call it `ZdpHelloResponseHeader`, but put only one field in it, `status`, a `u16`.  (Ignore the other fields for now… we'll circle back to them once SAs and link state is in place.)

In the inbound processor, you'll now need to handle messages of type `HelloRequest` – for these, you'll just want to send a message (using `enqueue_non_flow_pkt()`) of type `HelloReply` with a `ZdpHelloResponseHeader` body (hardcode `status` as 0 for now).  You can even reuse the same packet buffer like `Packet::new(pkt.destroy(), ...)`.  We can also print a message to stderr saying we got the `HelloRequest`.

Now, at startup, create a new task, which calls into the sync-request framework you made to send a `Hello` message.  It will need to get a buffer from the buffer stack, make it a packet, and "fill it in", but since the `Hello` message has no body there's nothing to do here.  Then it can just wait for a response, decode it as a `ZdpHelloResponseHeader`, and for now just print a message which also includes the value of the status field.

Now when you start the system, whichever half starts later should successfully send and receive a Hello message!  (The other half won't, because it won't retry.)  This is fine for now as it's just a test – later when we get link establishment going we'll have the `Hello` exchange wait for the SA to be established.

Blocked on:
- org-zpr/zpr-core#264

### PR DESCRIPTION
**Pull request by owenrhysthomas**

### CODE REVIEW

**Review by cpacejo — COMMENTED** [review]
This looks good!  Except `test/basic-test.sh` is failing for some reason.  I haven't had a chance to look into in but Wireshark might be helpful debugging:

```
$ RUST_BACKTRACE=1 test/basic-test.sh
Connecting...
Connected!
Wait for TUN carrier...
Connecting...
Connected!
Reporting for Duty!
Discard message recieved
Recieved HelloRequest
thread 'main' panicked at src/assembly.rs:128:22:
too-short inbound packet
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/panicking.rs:264:5
   3: core::option::expect_failed
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/option.rs:2030:5
   4: core::option::Option<T>::expect
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/option.rs:933:21
   5: ph_test::assembly::Assembly::send_sync_req_helper::{{closure}}
             at /home/cpacejo/projects/zpr-core/adapter/ph/src/assembly.rs:127:31
   6: ph_test::assembly::Assembly::send_sync_non_flow_req::{{closure}}
             at /home/cpacejo/projects/zpr-core/adapter/ph/src/assembly.rs:150:14
   7: ph_test::assembly::Assembly::send_hello_req::{{closure}}
             at /home/cpacejo/projects/zpr-core/adapter/ph/src/assembly.rs:209:14
   8: ph_test::main::{{closure}}
             at /home/cpacejo/projects/zpr-core/adapter/ph/src/main.rs:303:34
   9: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  10: tokio::runtime::coop::with_budget
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  12: tokio::runtime::park::CachedParkThread::block_on
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  15: tokio::runtime::context::runtime::enter_runtime
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  17: tokio::runtime::runtime::Runtime::block_on
             at /home/cpacejo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  18: ph_test::main
             at /home/cpacejo/projects/zpr-core/adapter/ph/src/main.rs:164:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
FAILURE
```

**Comment by owenrhysthomas** [comment]
The problem was because we were stripping the base header in inbound_processor_worker, before we sent the response message back on the `receiver`, but then in the assembly we were assuming that the packet still had the header, hence the too short message.

**Comment by owenrhysthomas** [comment]
The test is failing again now that I merged 264 into 265 -- looking into that now.

**Review by cpacejo — APPROVED** [review]
Perfect thanks!!

**Pull request merged**
