### PR TITLE
Mk addr message

### PR DESCRIPTION
**Pull request by mkolehmainen**
I believe we need an extra message from adapter to node following the key exchange.  I have doctored up the README diagram to illustrate.

Purpose of the message is to tell the node the ZPR address that the adapter is using.  

Normally this would get sorted out during a real authentication of the agent with the visa service.  Either the adapter would be permitted to use a ZPR address in its configuration or it would be given a dynamic one -- depending on policy.

We are not doing real authentication for m2.  Instead, just using the CN in the noise cert and having the node send a connect message to the visa service that says, "adapter with CN=x is at ZPR addr y".

Not sure what message type to hijack.  I would say either HelloRequest/Response or ConfigurationRequest/Response.  The response can just be a simple "ACK".  The request just needs to contain an IP address.

I'll update the diagram here when we figure it out.

### CODE REVIEW

**Comment by cpacejo** [comment]
How does this differ from Register Agent Address?

**Comment by mkolehmainen** [comment]
> How does this differ from Register Agent Address?

yes, that would be a good one to use.

**Comment by mkolehmainen** [comment]
Updated diagram, now using register-agent-address request/response.

**Review by cpacejo — DISMISSED** [review]
This matches my understanding now -- which FWIW I'm just following what Frank has laid out in RFC 6.5 draft 2 § 5.6.  Register Agent Address is step 6 (though Frank lists is as optional there, but mandatory elsewhere, I left a Q in the doc a while back for him).

(Aside -- once we implement Hello, that will occur directly between key exchange and Register Agent Address.)

**Review by svjaffer — COMMENTED** [review]
Technically, the diagram is also missing the hello message, which comes after the key management but before register agent address

**Comment by mkolehmainen** [comment]
> Technically, the diagram is also missing the hello message, which comes after the key management but before register agent address

@svjaffer -- are we doing the hello/hello-response messages for milestone2? 

(I heard offline that YES we will have hello in there, so will update diagram!)

**Pull request merged**
