### PR TITLE
cslab github workflow

### PR DESCRIPTION
**Pull request by owenrhysthomas**

### CODE REVIEW

**Comment by owenrhysthomas** [comment]
Not sure why `-D warnings` doesn't like loom, it's fine with it on my computer, but not on GitHub apparently. I'll look into it.

**Comment by cpacejo** [comment]
> Not sure why `-D warnings` doesn't like loom, it's fine with it on my computer, but not on GitHub apparently. I'll look into it.

Oh weird!!  It looks like we can add:
```
#[allow(unexpected_cfgs)]
```

to the top of `lib.rs`.

**Comment by owenrhysthomas** [comment]
> > Not sure why `-D warnings` doesn't like loom, it's fine with it on my computer, but not on GitHub apparently. I'll look into it.
> 
> Oh weird!! It looks like we can add:
> 
> ```
> #[allow(unexpected_cfgs)]
> ```
> 
> to the top of `lib.rs`.

Yes, I saw this, I wasn't sure if it would cause us to miss other errors, so I didn't add it yet, but I'll put that in.

**Review by cpacejo — APPROVED** [review]
Nice thanks for doing this!  Yes I think in general we don't want to disable the cfg warning but for this one build it's fine.

(Aside – some newlines wandered around, I just tacked on a couple commits to corral them back!)

**Pull request merged**
