### PR TITLE
Add ability to get MTU from a tokio UdpSocket on macos

### PR DESCRIPTION
**Pull request by mkolehmainen**
Bit of a hack but appears to work.

### CODE REVIEW

**Comment by cpacejo** [comment]
Does this query the path MTU or interface MTU?  For this API we want to query path MTU but if I'm reading the code correctly it appears to query the interface's MTU.  (Path MTU is essentially how we get from the kernel the information reported back by downstream hosts/routers via ICMP as to what _their_ MTU is.)

**Comment by cpacejo** [comment]
I'm having trouble finding leads how to get path MTU on macOS but this might be a way, by reading the routing table: https://stackoverflow.com/questions/76852711/macos-path-mtu-cache-doesnt-gets-properly-updated-when-pmtu-discovery-is-set

**Comment by cpacejo** [comment]
(That said I don't think we use this yet.  Its purpose is so we can properly reject too-large packets from the agent, rather than having them be blackholed, but that code doesn't exist yet.  So if to get the true PMTU requires a bit more work -- e.g. guess-and-checking by attempting to send our own ECHO packets, that is something we can put off for now.)

**Comment by mkolehmainen** [comment]
OMG I did the wrong thing then.  I failed to pay attention to what that function was supposed to be doing.

**Pull request closed without merging**
